### ISSUE TITLE
Find a strategy to purge deleted items

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#107]

**Comment by Natim** [comment]
There are two ways of handling that:

 - Having a list of the user devices and keeping track of the last collection_get for each of them. When the oldest update it's collection_get timestamp we can drop all deleted_items from the min(last_modified) of each devices.
 - Having a ttl on the purge telling: we just drop deleted_items older than a month.

The question is what happen in case we update our device more than a month after? Maybe then we can ask the client to do full collection_get sync as the first time.

**Comment by ametaireau** [comment]
@rnewman do you have some thoughts about that?

**Comment by rnewman** [comment]
List of devices would be ideal, but of course we don't really have a way to do that.

We could TTL, but I'd encourage that limit to be set higher; what's the longest break someone might have between using devices, and what's our goal in purging? Maybe 3 months is acceptable.

But I'd be inclined to measure and see. How often do people delete? Given that we only track the ID and a deletion flag, is it acceptable for 5% of our stored items to be deleted?

**Comment by rnewman** [comment]
My prediction: 95% of accounts won't ever delete an item. 90% of accounts will have fewer than ten total items. 99% of accounts will delete fewer than one item in twenty.

**Comment by ckarlof** [comment]
> But I'd be inclined to measure and see. 

I agree.

KISS: keep the tombstones around forever until we think they're causing a problem. My guess is that too many tombstones is a problem we want to have (i.e., RL is highly successful).

**Comment by Natim** [comment]
Ok this answer our question at short term. We should create a tool that will let ops purge items older than X days.
