### ISSUE TITLE
Authenticated requests are slow

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/readinglist#121]
![screen shot 2015-02-13 at 08 02 07](https://cloud.githubusercontent.com/assets/41547/6183580/f60c42b6-b356-11e4-9950-abbbf828ced1.png)

**Comment by Natim** [comment]
Yes we probably need to cache the Bearer Token verification. cc @rfk @ckarlof

**Comment by ckarlof** [comment]
We are working on our longer term story around this. It will likely involve some caching policy on the your side along with a notification system to inform you and other service providers of revocations and other events (https://github.com/mozilla/fxa-notification-server/blob/master/docs/api.md). This is a Q1 goal for us. 

Some additional information around this would be useful:
* I assume this is against our dev integration environment, or is this running locally?
* Can you please determine what the authentication overhead is, as measured by the RL server? It would be nice to compare this FxA dev vs FxA prod (or stage), too.

You could cache the tokens after you verify them on your side, but we need to figure out what the revocation story is. Caching them for some limited period of time will probably be a good short term tradeoff. We could also add a caching layer on the OAuth server for recently verified tokens. We should get some profiling data on the auth overhead first, though. Thoughts @rfk, @seanmonstar?

**Comment by seanmonstar** [comment]
I agree, it'd be nice to see the timing on the server side. Is that request doing more than verification?

**Comment by ckarlof** [comment]
@seanmonstar, in the meantime, we can also instrument `/verify` and see what the profile looks like there.

**Comment by rfk** [comment]
Yes, in the short-term caching will be the right thing here.  @Natim it would be great if you can confirm that most of the overhead here is in talking to the FxA oauth verifier.

If so, let's add a function/class/whatever for doing oauth token verifications in PyFxA, and have it take care of the caching internally.  Something like a 5min cache timeout to start is probably sufficient, and we can iterate on this class to have it e.g. consume revocation notifications in the future without having to change client code.

**Comment by Natim** [comment]
@rfk As you can see with PR #125 we are going from 1600ms per call to 2ms per call when enabling 5 minutes caching.

**Comment by rfk** [comment]
> we are going from 1600ms per call to 2ms per call when enabling 5 minutes caching 

Heh, great to hear and no great surprise.  We need to firm up the story here on our side.

**Comment by Natim** [comment]
Handled in https://github.com/mozilla-services/cliquet/pull/10
