### ISSUE TITLE
Support old versions when we increase the major

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/readinglist#153]
When we increase the major, we should also keep the old version of the service.

**Comment by tarekziade** [comment]
Are you talking about bacwkard compat' of the HTTP APIs?

**Comment by ametaireau** [comment]
Yes, this is it: how do we still handle the old majors when we publish a new one.

**Comment by ametaireau** [comment]
We'll think about it when needed (in case we have an incompatible version change)
