### ISSUE TITLE
Add "feature image"

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/readinglist#156]
On desktop in the ReadingList sidebar, we want to show an image representative of an article - the "feature image". Many pages specify this in metadata, but we also have a fallback to scrape through to find one in the page when we add a page.

I was sure this was already in the server data model... but checking it, I see it isn't (or was removed?).

Is it too late to add this to the data model? We only need a single URL value.

**Comment by rnewman** [comment]
This came up before, and some questions didn't have answers!

Being very much cross platform, and cross DPI — this same single URL might have to support an ident image for a 400dpi phone, a 300dpi 10" tablet, and a 96dpi Windows laptop — we need either spec guidelines or encoded attributes to describe how to select this, and when to ignore it.
