### ISSUE TITLE
build process exiting with linecache2

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/readinglist#177]
we bumped into https://github.com/testing-cabal/linecache2/issues/2

installing manually linecache2 in the virtualenv prior to running the build process fixed it, but we need that to be fixed upstream. This bug is mostly to track the problem and not forget about it.

**Comment by tarekziade** [comment]
I proposed a fix upstream https://github.com/testing-cabal/linecache2/pull/4

**Comment by Natim** [comment]
Well actually I am wondering if you guys are not trying to install dev-dependencies on the production server. Because linecache2 is a dependency of unittest2.

**Comment by Natim** [comment]
We should not install the ``install-dev`` Makefile rule (basically installing the dev-requirements file)  when building the RPM.

**Comment by tarekziade** [comment]
updating pip to the latest version fixes this. I propose that we "pip install --upgrade pip" in our makefile.

**Comment by tarekziade** [comment]
done now
