### ISSUE TITLE
Disable the fxa-oauth/login endpoints

### ISSUE THREAD

**Issue by Natim** [mozilla-services/readinglist#178]
Following bug https://bugzilla.mozilla.org/show_bug.cgi?id=1141166

As we won't have a WebClient for the production release, we don't need to activate the  fxa-oauth/login and fxa-oauth/token endpoints.

We will keep the fxa-oauth/params one with only the mandatory scopes

**Comment by ametaireau** [comment]
We want to split this out in a different repository (pyramid app) for better reusability. Goal is to not include it if not needed.

Some code could be used from https://github.com/spiral-project/daybed-fxa-oauth

**Comment by ametaireau** [comment]
It will be disabled by default with Cliquet 1.3
