### ISSUE TITLE
Include Git SHA in the /v1/ endpoint

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#188]
It would be nice if we could include the Git SHA of the commit that is deployed on a webserver (dev, stage, prod, etc) when we go to the /v1/ endpoint (ie: https://readinglist.stage.mozaws.net/v1/)
```json
{
  "url": "https://readinglist.stage.mozaws.net",
  "documentation": "https://readinglist.rtfd.org/",
  "version": "1.0",
  "hello": "readinglist"
}
```

For example, for fxa-content-server, we have https://latest.dev.lcip.org/ver.json:
```json
{
  "version": "0.33.0",
  "commit": "c46d67333bd72b74ad3f488c57952635475c7c13",
  "l10n": "6a338c7f59",
  "tosPp": "96dd1b5951"
}
```
(where the `l10n` and `tosPp` are the Git SHAs for the localization repo and legal repos (for our terms and privacy policies) respectively).

**Comment by Natim** [comment]
Yes we did something similar for loop as well which is really convenient.

 https://loop-dev.stage.mozaws.net/

**Comment by ametaireau** [comment]
The problem I see here is that the source distribution isn't dependent on git, and as such I don't see any way to get the git hash, any idea?

**Comment by Natim** [comment]
What we did in loop is to display it only if we have the info. On a dev server but on a production server we will just display the tag.

**Comment by Natim** [comment]
Fixed.
