### ISSUE TITLE
Versionned protocol

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#19]
* Discussion we had for loop https://bugzilla.mozilla.org/show_bug.cgi?id=1025792
* And for fxA https://mail.mozilla.org/pipermail/sync-dev/2013-September/000486.html

**Comment by Natim** [comment]
Described here: http://readinglist.readthedocs.org/en/latest/versionning.html#versionning
Implemented here: https://github.com/mozilla-services/readinglist/blob/master/readinglist/__init__.py#L43
