### ISSUE TITLE
Add API to delete ALL articles for a user?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#195]
As a user, I no longer want my articles stored in the readinglist.

I found https://github.com/mozilla-services/readinglist/wiki/API-Design-proposal#user-content-delete-articlesid but it looks like a per-article deletion, so I'd have to grab a list of articles, iterate over each one and delete it by ID, and then grab the next "page" of articles and start deleting again.

I'm not sure how many articles I have currently saved in Pocket, but last I checked it was over 900, so deleting all these individually or in batches of 25 could be time consuming.

Having a loaded foot-gun of an API that would let me delete all currently stored articles would potentially be useful.

**Comment by Natim** [comment]
Actually you have got the ``DELETE /articles`` endpoint to do that.

**Comment by pdehaan** [comment]
Oh! I didn't see it in https://github.com/mozilla-services/readinglist/wiki/API-Design-proposal
This may just be a doc bug/enhancement. \o/

**Comment by leplatrem** [comment]
Well, the API design proposal may be out of date, the official doc is http://readinglist.readthedocs.org/en/latest/resource.html#delete-articles

**Comment by pdehaan** [comment]
Sweet, thanks. Closing this as RTFM (now that I'm looking at the right "M").

:heart:
