### ISSUE TITLE
Support batching

### ISSUE THREAD

**Issue by rnewman** [mozilla-services/readinglist#2]
We expect to occasionally issue large numbers of changes at once. Four scenarios that immediately come to mind:

• After a period of disconnected operation — reading on a long-haul flight. We'll be updating the 'read' status of a number of records at once.
• After an outage. 
• First run. We already have users with lots of items in their Android reading lists, and we don't expect to force future users to sign up with an account before saving items to their list.
• Post-import. It's easy to imagine that we'll support import from similar services. We definitely don't want to issue 1000+ individual HTTP requests after an import.

This implies that we need:

• A batching API for issuing changes to existing items.
• A batching API for inserts, which has the added complication of having to assign and return GUIDs for the new items.

**Comment by ametaireau** [comment]
Should we support that through Keep Alive ? https://en.wikipedia.org/wiki/HTTP_persistent_connection

**Comment by rnewman** [comment]
I'm a little skeptical about using keepalive as a substitute for batching. I think it's generally expected that we'll use it for transport-level efficiency, and we probably already do so, but I don't think it obviates the need for real batching.

Here are some reasons why:

* It muddles the concept of transaction and timestamp boundaries, which might be important, and which can be well-specified for explicit batches.
* It's less efficient than real batching — although the socket is still open, each individual request within the connection still needs to be created on the client, include a full set of headers, be dispatched and authorized on the server, have the response parsed and callbacks invoked, etc. etc.
