### ISSUE TITLE
Add a smoke test for production

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/readinglist#202]
We should be able to test production with a smoke test. We'll need to use a test FxA user for that, not sure how to get the right credentials, though.

**Comment by rfk** [comment]
I suggest just using a test address on http://restmail.net/ to create the testing account.  We have other automated tests that run against prod using `@restmail.net` addresses already, e.g. browser integration tests.

**Comment by ametaireau** [comment]
Will that get me a FxA bearer token?

**Comment by rfk** [comment]
You'd have to go through the full auth dance with fxa-auth and fxa-oauth to do so.  But I guess since our tokens are currently immortal, you could do this by hand once and then just re-use the token directly for smoketesting.
