### ISSUE TITLE
503 cloudy error if you request an article with a random id

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#209]
### Steps to reproduce:
1. Open https://readinglist.stage.mozaws.net/v1/articles/foobar in your browser (or do a GET request w/ cURL or httpie in your Terminal &mdash; whatever).

### Actual results:

> ```
<html>
<head><title>503 Service Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Cloudy: Try again later. </h1></center>
</body>
</html>
```

I'm pretty sure the server is OK since if I request GET /v1/articles, I get this response:
```json
{"items": []}
```

And GET /v1/__heartbeat__ returns:
```json
{"database": true}
```

What's super odd though, is that when I request GET /v1/articles, I _SOMETIMES_ get this response:
```json
{
  "errno": 111,
  "message": "The resource your are looking for could not be found.",
  "code": 404,
  "error": "Not Found"
}
```

**Comment by leplatrem** [comment]
For the last one I don't see any reason, but for the 503 instead of 404, I know what happens!

@ametaireau to give you a hint, it does not occur when using a uuid :) https://readinglist.stage.mozaws.net/v1/articles/de305d54-75b4-431b-adb2-eb6b9e546013

**Comment by pdehaan** [comment]
Retesting this, but it looks like now instead of HTML response I'm getting JSON from httpie:
```sh
$ http GET https://readinglist.stage.mozaws.net/v1/articles/foobar --auth="pdehaan:"
HTTP/1.1 503 Service Unavailable
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Last-Modified
Connection: keep-alive
Content-Length: 124
Content-Type: application/json; charset=UTF-8
Date: Wed, 01 Apr 2015 21:43:09 GMT
Retry-After: 30

{
    "code": 503,
    "errno": 201,
    "error": "Service Unavailable",
    "message": "Service unavailable due to high load, please retry later."
}


$ http GET https://readinglist.stage.mozaws.net/v1/articles --auth="pdehaan:"
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified
Backoff: None
Connection: keep-alive
Content-Length: 12
Content-Type: application/json; charset=UTF-8
Date: Wed, 01 Apr 2015 21:43:42 GMT
Last-Modified: 1427924622360
Total-Records: 0

{
    "items": []
}
```

**Comment by leplatrem** [comment]
Currently adressed by https://github.com/mozilla-services/cliquet/pull/208

**Comment by Natim** [comment]
Fixed
