### ISSUE TITLE
Better default value for _limit

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#214]
I currently have 1316 items in my reading list (user: pdehaan), and when I go to https://readinglist.stage.mozaws.net/v1/articles it returns all 1316 items with a `Content-Length` of 674388 (~659 KB)

```
HTTP/1.1 200 OK
Date: Thu, 26 Mar 2015 00:06:31 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 674388
Connection: keep-alive
Last-Modified: 1427328351337
Total-Records: 1316
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified
Backoff: None
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Max-Age: 1728000
Access-Control-Allow-Headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Conditions-Accepted
```

I can set an explicit [`_limit`](https://readinglist.readthedocs.org/en/latest/api/resource.html#paginate) to control how many records I want so I can paginate, but I'm not sure if returning ALL records by default is great.
I know GitHub sets a maximum response of 100 items via their API. Not sure if we want to set a default of 100-200 articles and maybe do some sort of hard limit of 100-200 results per batch.

```js
var _limit = Math.min(parseInt(options._limit, 10), 100);
```
Or whatever the Python syntax would be for that not-very-pretty code.

**Comment by leplatrem** [comment]
This is already implemented, but disabled by default.

Add ``cliquet.paginate_by = 100`` in settings and it will do what you expect here :)

**Comment by pdehaan** [comment]
OK, but should we enable it on stage/prod?

I imagine that I can easily write my `for()` loop to create 100000 records on the server and then just keep requesting a few MB of results until I kill the server's resources.
