### ISSUE TITLE
add more info on heartbeat

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/readinglist#229]
The heartbeat API should ping *all* backends the reading list project uses, not just the database.

Would it make sense to ping FxA ?

**Comment by tarekziade** [comment]
cc @bobm

**Comment by pdehaan** [comment]
Not sure what "ping" means, or if bobm was suggesting that the `/v1/__heartbeat__` endpoint attempts to do a full `make smoke` test since it's a very small load test (although still took ~9s for me, which may be too much for a simple heartbeat check).

```
$ time make smoke
.venv/bin/loads-runner --config=./config/smoke.ini --user-id=pdehaan --server-url=https://readinglist.stage.mozaws.net:443 loadtest.TestBasic.test_all

Duration: 8.71 seconds
Hits: 41
Started: 2015-03-27 21:35:43.252934
Approximate Average RPS: 4
Average request time: 0.19s
Opened web sockets: 0
Bytes received via web sockets : 0

Success: 1
Errors: 0
Failures: 0


Slowest URL: https://readinglist.stage.mozaws.net:443/v1/batch 	Average Request Time: 0.718262

Stats by URLs:
- https://readinglist.stage.mozaws.net:443/v1/batch                        	Average request time: 0.718262	Hits success rate: 1.0
- https://readinglist.stage.mozaws.net:443/v1/articles                     	Average request time: 0.179836230769	Hits success rate: 1.0
- https://readinglist.stage.mozaws.net:443/v1/articles?_limit=5&_sort=title	Average request time: 0.101994	Hits success rate: 1.0

real	0m9.262s
user	0m0.334s
sys 	0m0.186s
```

**Comment by Natim** [comment]
A smoke test would be too much but we should definitely verify the connection with FxA. Maybe the FxA server does have a __heartbeat__ endpoint that we could ping cc @rfk

**Comment by Natim** [comment]
See https://github.com/mozilla/fxa-oauth-server/issues/238

**Comment by pdehaan** [comment]
@Natim See https://github.com/mozilla/fxa-oauth-server/issues/238#issuecomment-87768836

> _it does a db ping and if that fails the status code will not be 200. hopefully the status code should be enough_

There is a \_\_heartbeat\_\_ endpoint for oauth server. Looks like it returns a statusCode === 200 on success and 500 on fail.

- stage: https://oauth.stage.mozaws.net/__heartbeat__
- prod: https://oauth.accounts.firefox.com/__heartbeat__

**Comment by Natim** [comment]
Handled here: https://github.com/mozilla-services/cliquet/pull/184

**Comment by pdehaan** [comment]
Will the __heartbeat__ endpoint notify us if there is an issue w/ DB connection limits?

**Comment by Micheletto** [comment]
+1 to the DB connection check for __heartbeat__, we need this.  The code linked above seems specific to Redis, but perhaps I'm not reading it correctly.

**Comment by leplatrem** [comment]
Yes the heartbeat will fail (i.e. return 503) and return a JSON with 3 status:
* database : *can read and write on the DB backend*
* cache : *can read and write on the cache backend*
* oauth :  *oauth server heartbeat returns 200*

**Comment by tarekziade** [comment]
So the bad news is that the heartbeat did not fail when Margaret started to have some 503s for some reason.

After some discussion with Bob, we're thinking it would be great to have the heartbeat actually acting like a real client under a specific user_id and randomly do one of those actions (using the same **view** code and bypassing the auth) to have better chances to catch a connection or pool error :

- add a batch of 5 URLs for user_id 0   (66% of the time)
- delete all URLs for user_id 0 if any.    (33% of the time)

The heartbeat is called once a minute so it's fine to do this.
