### ISSUE TITLE
drop pserve

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/readinglist#230]
let's drop pserve and use wsgi with 2 processes on local runs and on travis

That'll help catching earlier any bugs related to this stack

**Comment by Natim** [comment]
Yes but in development we need the auto-reload functionnality as well as the possibility to use pdb. It does looks possible with uwsgi.

**Comment by tarekziade** [comment]
auto reload

```
[uwsgi]
py-autoreload = 1
```

For pdb you need the honour stdin option

```
[uwsgi]
honour-stdin = 1
```

however in that case you need to run a single process or it's going to be a mess :)

**Comment by Natim** [comment]
Perfect then :)
