### ISSUE TITLE
Login prompt on prod

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/readinglist#237]
### Steps to reproduce:
1. Go to https://readinglist.services.mozilla.com/v1/articles

### Actual results:
![problem_loading_page](https://cloud.githubusercontent.com/assets/557895/6955665/43f374fe-d896-11e4-888d-8e65adcc8bca.png)

Closing the dialog box displays this JSON output in the browser:
```js
{
  "errno": 104,
  "message": "Please authenticate yourself to use this endpoint.",
  "code": 401,
  "error": "Unauthorized"
}
```

### Expected results:
No "Authentication Required" popup.

**Comment by Natim** [comment]
This is because we have Basic Auth activated. It is a feature of browser which supports Basic Auth.

**Comment by Natim** [comment]
Actually BasicAuth is not activated in production. So this is a bug I can reproduce.

**Comment by Natim** [comment]
Apparently it is because of the ``WWW-Authenticate`` header.

**Comment by ametaireau** [comment]
We should disable this on production!

**Comment by ametaireau** [comment]
This should be disabled in production, per https://github.com/mozilla-services/puppet-config/blob/master/readinglist/yaml/app/readinglist.prod.yaml#L19

**Comment by Natim** [comment]
Actually Basic Auth is disabled but the prompt is not.
