### ISSUE TITLE
Add a Redis storage backend

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#27]
https://github.com/yohanboniface/redis-limpyd

**Comment by ametaireau** [comment]
I wonder if we really want to use redis here.

We should probably do a comparison between the different databases that could match our needs and see which would be the best fit. I personally like redis a lot, but some stuff may not be easy to implement (pagination, filtering, this kind of things).

+1 for exploring all this and making the call once we know more, though.

**Comment by Natim** [comment]
This is what made me think redis could be a great idea: https://github.com/mozilla-services/readinglist/blob/switch_to_cornice/readinglist/backend/memory.py#L10-L47

**Comment by leplatrem** [comment]
Available in https://github.com/mozilla-services/readinglist/releases/tag/0.1
