### ISSUE TITLE
Read position should not be expressed as a percentage

### ISSUE THREAD

**Issue by rnewman** [mozilla-services/readinglist#3]
Consider a typical "longreads"-style article of 3,000–10,000 words.

An integer percentage might only give us a granularity of 100 or more words. Even my large-screen HTC phone at a typical zoom level fits 12 lines of 4-5 words each, so a single integer percentage point is *two screens* of text.

We'll need to adjust this to be something more fine-grained. Pocket uses a word count. We know (Bug 1106380) that this isn't perfectly localizable, but it's probably adequate for scroll position.

**Comment by Unfocused** [comment]
I'm worried this will introduce jank when we open a particularly long article and restore the scroll position based on word count. It's also going to be a reasonable amount of computation when we want to regularly save the read position.
