### ISSUE TITLE
Take advantage of Hawk sessions

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#36]
Currently, we verify the Bearer token on FxA on each request.

We can imagine caching the verification (e.g. for 10 minutes) to avoid network overhead.

Also, we could use Hawk sessions.

https://github.com/mozilla-services/readinglist/wiki/API-Design-proposal#hawk

**Pros and cons**

* Session is persisted in the API, the bearer token is not checked at each request
* If FxA is down, sessions may still allow to authenticate requests
* User authentication could be decorrelated from Firefox Accounts
* Clients could start using the API without FxA (e.g. single device)
* Requests cannot be replayed by an attacker
* Obtained Hawk tokens cannot be used anywhere else, contrary to Bearer token which can be reused within the whole FxA eco-system

**Comment by ncalexan** [comment]
Thoughts:

* One of the motivations of the oauth approach was to make it *easier* for web pages to interact with FxA-authenticated services.  Doing an oauth dance and then a bunch of client-side Hawk crypto doesn't seem like a good trade-off.  I don't think Google services require this style of token exchange, for example.  (There is a credential refresh, but I think it's just "get me another oauth token".)  Am I wrong?

* Decoupling auth from FxA sounds like an anti-goal.  Tell me a story about a cloud-backed reading list that's useful with a single device and some non-account backed interface.

* The Bearer oauth token can be scoped to just the reading list, or even just one aspect of the list (read, write, view, etc).  I'm not that concerned about a leaked oauth token destroying a user's FxA ecosystem.

* Are we really concerned about replay attacks?  Everything here is behind TLS.

**Comment by Natim** [comment]
This is exactly the reason why we opened Bug 1123710: https://bugzilla.mozilla.org/show_bug.cgi?id=1123710

Do you have any answer to the other questions there?

**Comment by Natim** [comment]
@ckarlof answered here https://bugzilla.mozilla.org/show_bug.cgi?id=1123710
