### ISSUE TITLE
Control retry-after and backoff on running instances

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/readinglist#38]
Provide a way to set backoff or retry after values on running instances.
Since configuration is likely to be under version control etc, ops might want an easier way to temporarily set those values

* ``/__admin__`` endpoint ?
* POSIX Signals ?

**Comment by Natim** [comment]
@deanwilson @Micheletto any though about how you would like to be able to configure that?

**Comment by Natim** [comment]
So the path forward is to change the configuration file and then use ``killall -HUP uwsgi``
