### ISSUE TITLE
Support full range of article data

### ISSUE THREAD

**Issue by rnewman** [mozilla-services/readinglist#5]
Here's the list we came up with.

---

* item_id

The values provided by the client when added:
* given_url
* given_title

The values retrieved from the fetched content:
* resolved_url
* resolved_title
* excerpt -- raw text for now
* status -- 0 OK, 1 archived, 2 deleted
* favorite -- 0 or 1
* is_article -- 0 or 1
* word_count

* unread: 0 or 1
* added_by: name of device.
* added_on: timestamp, device local
* stored_on: timestamp
* marked_read_by:
* marked_read_on:

It looks like you've split out devices, so `added_by` etc. can be device references instead of strings, but you'll have to consider what happens when a device is removed — it shouldn't remove the articles it added!

**Comment by ametaireau** [comment]
> Re is_article: we support adding things to the reading list that aren't long-form text. This flag being 0 means that the client shouldn't expect to get an article view out of this item.

I don't quite understand what this is for, by reading your comment (sorry ;)). Can you elaborate with an example of what an article would be if its `is_article` attribute is set to `0`? (Then, should it still be an article? I feel something a bit weird by having an Article which in fact isn't one).

**Comment by rnewman** [comment]
For example: a YouTube URL. Nothing stops me from adding that to my reading
list (Pocket calls theirs a queue for a reason), but it's not an article.
There's no excerpt, no extracted text to show in reader mode.

**Comment by leplatrem** [comment]
Available in https://github.com/mozilla-services/readinglist/releases/tag/0.1
