### ISSUE TITLE
Freeze the Python version

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/readinglist#56]
What's the Python version for the project ? let's freeze it by making sure the makefile works only on that version.

**Comment by Natim** [comment]
We are supporting the tox matrix which are py26, py27 and py34

**Comment by tarekziade** [comment]
Nevertheless, we need to pick a version that will be released in production.

**Comment by Natim** [comment]
I don't get why this is important ?

We hope it will be Python 3.4 but it is OPS call to decide.

**Comment by tarekziade** [comment]
I don't see the point to maintain several Python 2/3 versions for this service and waste some time in str/bytes/six conversions. The only "customer" right now is us.

So if python 3.4 is the target, let's drop Python 2 and check with ops that they're good with 3.4

**Comment by Natim** [comment]
The point is to prevent from UnicodeDecodeError if py26 is the target. And to make sure it also work with py27 in that case.

**Comment by tarekziade** [comment]
if py26 is the target, why do you want to make sure it also works in py27 ?

Let's pick a version and have it approved by ops. I guess 3.4 would be nice

**Comment by tarekziade** [comment]
I have sent an e-mail to Ops and asked if 3.4 was fine. Will comment here depending on the answer.

**Comment by Natim** [comment]
Maybe because 2.7 is the last Python 2 version and Python 2.6 is legacy.

**Comment by tarekziade** [comment]
ok let's back up a little bit.

Do this:

1/ pick a python version: 2.6 or 2.7 or 3.4  (the one you think it's best for the project - I said 3.4 but it'sup to you) 
2/ submit it to ops
3/ use this version in the code
4/ drop any code that exists to support several Python versions.

In case you think we should support more than one Python version, explain why.

**Comment by ametaireau** [comment]
I concur with @natim here. We can support multiple python versions, and because we have done it from the beginning, it actually will cost us more to stop the support for other python versions rather than keeping it.

Supporting multiple python versions enables multiple people to install the server on their machines. Also, supporting newer versions of python also enables us to limit the amount of work we would need to do in case ops want to support older versions.

That being said, I also believe we should decide which python version we will have on production and test on the staging environment with the same version.

**Comment by tarekziade** [comment]
> We can support multiple python versions, and because we have done it from the beginning, it actually will cost us more to stop the support for other python versions rather than keeping it.

This is not a good reason - You can't say that "it's too late" on a code base that is roughly a month old and that we will probably grow and maintain for years.

Supporting Python 2 and 3 adds complexity. I don't see any benefit in keeping it going forward. Maintaining a more complex code base will cost us more in the long term. 

> Supporting multiple python versions enables multiple people to install the server on their machines.

By people do you mean the community ? defining a Python version for this project will not disable people from installing the server on their machines since Python 2 and Python 3 are available on all platforms now. Unless you are aiming at Python <= 2.6.

> Also, supporting newer versions of python also enables us to limit the amount of work we would need to do in case ops want to support older versions.

Why would you do less work by supporting a newer version of Python and releasing the project under an older version ? I am confused.

> That being said, I also believe we should decide which python version we will have on production and test on the staging environment with the same version.

I still don't see any good reason to maintain several Python versions for this project. I am pretty sure ops will be fine with 3.4 - let's wait and see.

**Comment by leplatrem** [comment]
Since the target is python 2.7, I suggest we go on with *six* with forward compatibility with python 3.4

i.e. change nothing :)

**Comment by Natim** [comment]
Yep.
