### ISSUE TITLE
Consider supporting conditional change operations

### ISSUE THREAD

**Issue by rnewman** [mozilla-services/readinglist#6]
Some frequent client operations are best expressed as conditional changes: “mark this as read if it's currently unread”, “move this to the archive unless it's deleted”, “set marked-as-read-on and marked-as-read-by to these values if they're currently not set”.

These avoid races such as the following:

* Board plane.
* On your iPad, you archive an item. You put the iPad away.
* On your phone, you decide that it's rubbish, so you delete the item.
* Phone goes online.
* iPad goes online (wifi).

Expected: item is deleted. Blind deletions trump blind archives.
Actual: item is archived (iPad sends its “move this to the archive” change after the deletion), or iPad makes two HTTP requests.

These operations are interesting in that they're trivial to apply 'locally': either their condition is met and the change is applied, or the condition is not met and they're discarded.

It would be possible to do this remotely via the following:

* Client downloads each record that it's about to modify.
* Client reconciles changes according to expected conditional behavior.
* Client uploads changes with an X-If-Unmodified-Since header to detect conflicting writes.
* Repeat until upload succeeds without a conflict.

This is how Sync works (because the server can't see the cleartext). With the reading list service, we can do better, because the server can see the canonical cleartext. It can do the following:

* Client uploads a collection of changes (like a patch, but semantic: not `[{id: 'abcde', state: archived}]`, but `{archive: ['abcde']}`).
* Server replies with updated state: `{deleted: ['abcde']}`.

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla-services/readinglist/pull/77
